// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqQW2sA7kSFO1v3e0JFcv46KwIIQ1BdOQ',
    appId: '1:307393429746:web:e89e18180812e824c7d06b',
    messagingSenderId: '307393429746',
    projectId: 'shakuyosho-app',
    authDomain: 'shakuyosho-app.firebaseapp.com',
    storageBucket: 'shakuyosho-app.firebasestorage.app',
    measurementId: 'G-9NSSH2X6SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFB1wuIStSd57w5eJhM_3h3nYJc3RF8LU',
    appId: '1:307393429746:android:962e5a3bd49d79f2c7d06b',
    messagingSenderId: '307393429746',
    projectId: 'shakuyosho-app',
    storageBucket: 'shakuyosho-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0OFI5KNO6W048OcdSj2sCFMIDbYz_sM8',
    appId: '1:307393429746:ios:65f4b343031658c4c7d06b',
    messagingSenderId: '307393429746',
    projectId: 'shakuyosho-app',
    storageBucket: 'shakuyosho-app.firebasestorage.app',
    iosBundleId: 'com.example.shakuyoushoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0OFI5KNO6W048OcdSj2sCFMIDbYz_sM8',
    appId: '1:307393429746:ios:65f4b343031658c4c7d06b',
    messagingSenderId: '307393429746',
    projectId: 'shakuyosho-app',
    storageBucket: 'shakuyosho-app.firebasestorage.app',
    iosBundleId: 'com.example.shakuyoushoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqQW2sA7kSFO1v3e0JFcv46KwIIQ1BdOQ',
    appId: '1:307393429746:web:98b19fee26f99f52c7d06b',
    messagingSenderId: '307393429746',
    projectId: 'shakuyosho-app',
    authDomain: 'shakuyosho-app.firebaseapp.com',
    storageBucket: 'shakuyosho-app.firebasestorage.app',
    measurementId: 'G-H9BCHFWJQ6',
  );
}
